import { Resend } from "resend";
export const resend = new Resend(process.env.RESEND_API_KEY);

interface Item { name: string; quantity: number; price: number }
export function ownerHtml(p: { orderNumber: string; buyerName: string; buyerPhone: string; buyerEmail?: string; deliveryAddress: string; notes?: string; items: Item[]; total: number; waUrl: string }) {
  const rows = p.items.map(i => `<tr><td style="padding:6px 0;border-bottom:1px solid #f0ede8">${i.name} ×${i.quantity}</td><td style="text-align:right;padding:6px 0;border-bottom:1px solid #f0ede8;font-weight:600">Rs.${(i.price*i.quantity).toLocaleString()}</td></tr>`).join("");
  return `<!DOCTYPE html><html><body style="font-family:Inter,Arial,sans-serif;background:#f4f1ec;margin:0;padding:20px"><div style="max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden"><div style="background:linear-gradient(135deg,#D72638,#FF8C00);padding:28px;text-align:center"><h1 style="color:#fff;margin:0;font-size:20px">🎨 New Order — ${p.orderNumber}</h1><p style="color:rgba(255,255,255,0.85);margin:6px 0 0">Rs.${p.total.toLocaleString()}</p></div><div style="padding:28px"><table style="width:100%;background:#fafaf8;border-radius:10px;padding:16px;margin-bottom:20px;border-collapse:collapse"><tr><td style="color:#888;font-size:13px;padding:3px 0">Customer</td><td style="font-weight:600">${p.buyerName}</td></tr><tr><td style="color:#888;font-size:13px;padding:3px 0">Phone</td><td>${p.buyerPhone}</td></tr><tr><td style="color:#888;font-size:13px;padding:3px 0">Email</td><td>${p.buyerEmail||"—"}</td></tr><tr><td style="color:#888;font-size:13px;padding:3px 0">Address</td><td>${p.deliveryAddress}</td></tr>${p.notes?`<tr><td style="color:#888;font-size:13px;padding:3px 0">Notes</td><td>${p.notes}</td></tr>`:""}</table><table style="width:100%;border-collapse:collapse">${rows}</table><div style="text-align:right;font-size:18px;font-weight:700;color:#D72638;padding-top:12px;border-top:2px solid #D72638;margin-top:8px">Rs.${p.total.toLocaleString()}</div><a href="${p.waUrl}" style="display:block;margin-top:20px;background:#25D366;color:#fff;text-align:center;padding:14px;border-radius:10px;text-decoration:none;font-weight:700">Reply on WhatsApp</a></div></div></body></html>`;
}
export function buyerHtml(p: { orderNumber: string; buyerName: string; buyerPhone: string; items: Item[]; total: number; address: string }) {
  const rows = p.items.map(i => `<tr><td style="padding:6px 0">${i.name} ×${i.quantity}</td><td style="text-align:right;padding:6px 0;font-weight:600">Rs.${(i.price*i.quantity).toLocaleString()}</td></tr>`).join("");
  return `<!DOCTYPE html><html><body style="font-family:Inter,Arial,sans-serif;background:#f4f1ec;margin:0;padding:20px"><div style="max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden"><div style="background:linear-gradient(135deg,#D72638,#FF8C00);padding:28px;text-align:center"><h1 style="color:#fff;margin:0;font-size:22px">Thank you, ${p.buyerName}! 🎉</h1><p style="color:rgba(255,255,255,0.85);margin:8px 0 0">Order ${p.orderNumber} confirmed</p></div><div style="padding:28px"><table style="width:100%;border-collapse:collapse">${rows}</table><div style="text-align:right;font-size:18px;font-weight:700;color:#D72638;padding-top:12px;margin-top:8px;border-top:2px solid #D72638">Rs.${p.total.toLocaleString()}</div><div style="margin-top:24px;background:#fafaf8;border-radius:10px;padding:16px"><h3 style="margin:0 0 10px;font-size:15px">What happens next?</h3><p style="margin:4px 0;font-size:14px">✅ We'll call you on <b>${p.buyerPhone}</b> to confirm</p><p style="margin:4px 0;font-size:14px">📦 We'll prepare your order carefully</p><p style="margin:4px 0;font-size:14px">🚚 Delivery to: ${p.address}</p><p style="margin:4px 0;font-size:14px">💚 <b>Pay on delivery — no advance needed!</b></p></div><p style="text-align:center;color:#aaa;font-size:12px;margin-top:24px">Roja International — Sri Lanka's Colour Store</p></div></div></body></html>`;
}
